# Utilisation de l'image Tomcat officielle comme base
FROM openjdk:17

# Copier le fichier WAR de l'application dans le répertoire webapps de Tomcat
COPY ./target/api.mushroom-0.0.1-SNAPSHOT.war /usr/local/tomcat/webapps/

# Set the working directory to /app
WORKDIR /app

# Copy the executable into the container at /app
ADD target/*.jar app.war

# Make port 8080 available to the world outside this container
# EXPOSE 8080

# Commande par défaut à exécuter
CMD ["java", "-jar", "/app/app.war"]