drop table if exists edibility CASCADE 
drop table if exists lamella_type CASCADE 
drop table if exists localname CASCADE 
drop table if exists localname_mushroom_entities CASCADE 
drop table if exists media CASCADE 
drop table if exists mushroom CASCADE 
drop table if exists mushroom_localname CASCADE 
drop table if exists user CASCADE 
create table edibility (id bigint generated by default as identity, name varchar(255), primary key (id))
create table lamella_type (id bigint generated by default as identity, type varchar(255), primary key (id))
create table localname (id bigint generated by default as identity, created_at timestamp, name varchar(255), primary key (id))
create table localname_mushroom_entities (localname_entity_id bigint not null, mushroom_entities_id bigint not null, primary key (localname_entity_id, mushroom_entities_id))
create table media (id bigint generated by default as identity, created_at timestamp, name varchar(255), path varchar(255), id_mushroom bigint not null, primary key (id))
create table mushroom (id bigint generated by default as identity, comment varchar(255), commonname varchar(255) not null, created_at timestamp, flesh varchar(255), foot varchar(255), habitat varchar(255), hat varchar(255), lamella varchar(255), latinname varchar(255), updated_at timestamp, visibility boolean, id_edibility bigint, id_lamella bigint, id_user bigint, primary key (id))
create table mushroom_localname (id_mushroom bigint not null, id_localname bigint not null, primary key (id_mushroom, id_localname))
create table user (id bigint generated by default as identity, created_at timestamp, email varchar(255), firstname varchar(255), lastname varchar(255), password varchar(255), pseudo varchar(255), role varchar(255), updated_at timestamp, primary key (id))
alter table localname_mushroom_entities add constraint FKq7e1i899q6mjri007em82mw10 foreign key (mushroom_entities_id) references mushroom
alter table localname_mushroom_entities add constraint FKqy4u0c8qhefolb4w8atipqtn9 foreign key (localname_entity_id) references localname
alter table media add constraint FK45us9u8ak17q3vkogwnhfaijv foreign key (id_mushroom) references mushroom
alter table mushroom add constraint FK2vu1vofbb8obljdobq30sm1go foreign key (id_edibility) references edibility
alter table mushroom add constraint FK36g2oo3iuwrnvfctigxiu4ben foreign key (id_lamella) references lamella_type
alter table mushroom add constraint FKao37vbqbs1b670y3dp8gr098n foreign key (id_user) references user
alter table mushroom_localname add constraint FKig6knojsp06gs29ri13ihib8m foreign key (id_localname) references localname
alter table mushroom_localname add constraint FKinr13esyxs6u5qg01gmqqlr0e foreign key (id_mushroom) references mushroom
