# Nom du workflow
name: Build and Deploy Spring Boot Application

# Événement qui déclenche le workflow
on:
  push:
    branches:
      - main # Branche sur laquelle le workflow sera exécuté

# Définition des tâches à exécuter
jobs:
  build-and-deploy: # Nom de la tâche
    runs-on: ubuntu-latest # Système d'exploitation sur lequel la tâche sera exécutée

    steps: # Liste des étapes à exécuter
      - name: Checkout code # Nom de l'étape
        uses: actions/checkout@v2 # Action qui clone le dépôt GitHub sur le runner

      - name: Set up JDK 17 # Nom de l'étape
        uses: actions/setup-java@v2 # Action qui installe le JDK 17 sur le runner
        with:
          java-version: '17' # Version du JDK à installer
          distribution: 'adopt' # Distribution du JDK à installer

      - name: Build with Maven # Nom de l'étape
        run: mvn clean package -DskipTests --file pom.xml # Commande qui construit l'application Spring Boot avec Maven

      - name: Copy WAR file to Tomcat webapps directory # Nom de l'étape
        run: |
          echo "Déploiement sur le VPS"
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_LOVA }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Vérifier la connexion au VPS
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa lova@151.80.148.111 'exit 0'
          if [ $? -eq 0 ]; then
            echo "Connexion au VPS établie"
            # Déployer le fichier WAR
            sudo -u lova scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa target/mushroomkingdom-api.war lova@151.80.148.111:/opt/tomcat/apache-tomcat-10.1.23/webapps/mushroomkingdom-api.war
            # Redémarrer Tomcat
            ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa lova@151.80.148.111 'sudo systemctl restart tomcat'
          else
            echo "Échec de la connexion au VPS"
            exit 1
          fi